### ISSUE TITLE
Polite Request, please include our new LLM Hallucination leaderboard, NYT article and accompanying model and blog post

### ISSUE THREAD

**Issue by simonhughes22** [EdinburghNLP/awesome-hallucination-detection#4]
This site has been an invaluable resource in doing the work linked below. We'd love it if you'd add us to the list. We were recently interviewed for the new york times:

https://www.nytimes.com/2023/11/06/technology/chatbots-hallucination-rates.html

LLM Hallucination Leaderboard: https://github.com/vectara/hallucination-leaderboard/blob/main/README.md
Blog posting: https://vectara.com/cut-the-bull-detecting-hallucinations-in-large-language-models/
Hugging Face model: https://huggingface.co/vectara/hallucination_evaluation_model

Thanks, keep up the great work.

**Comment by pminervini** [comment]
feel free to do a pull request!

**Comment by simonhughes22** [comment]
Ah ok, this is GH! Will do
